# docker-compose.yaml
version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: credit_system_db
    environment:
      POSTGRES_USER: credit_user
      POSTGRES_PASSWORD: credit_pass
      POSTGRES_DB: credit_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U credit_user -d credit_system"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: